name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: tshirts fail
      run: |
        g++ -Wall -Wextra -Werror tshirts.cpp test_tshirts.cpp -o tshirts.out
        bash .github/workflows/expectfail.sh ./tshirts.out

    - name: misaligned fail
      run: |
        g++ -Wall -Wextra -Werror misaligned.cpp test_misaligned.cpp -o misaligned.out
        bash .github/workflows/expectfail.sh ./misaligned.out

    - name: alerter fail
      run: |
        g++ -Wall -Wextra -Werror alerter.cpp test_alerter.cpp -o alerter.out
        bash .github/workflows/expectfail.sh ./alerter.out
